/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['server.js']) {
  _$jscoverage['server.js'] = [];
  _$jscoverage['server.js'][1] = 0;
  _$jscoverage['server.js'][2] = 0;
  _$jscoverage['server.js'][3] = 0;
  _$jscoverage['server.js'][4] = 0;
  _$jscoverage['server.js'][5] = 0;
  _$jscoverage['server.js'][6] = 0;
  _$jscoverage['server.js'][7] = 0;
  _$jscoverage['server.js'][11] = 0;
  _$jscoverage['server.js'][13] = 0;
  _$jscoverage['server.js'][14] = 0;
  _$jscoverage['server.js'][15] = 0;
  _$jscoverage['server.js'][19] = 0;
  _$jscoverage['server.js'][22] = 0;
  _$jscoverage['server.js'][25] = 0;
}
_$jscoverage['server.js'].source = ["var http = require(\"http\");","var url = require(\"url\");","function start(route, handle, connectDB, chatServer) {","    dbConnected = false;","    connectDB(function(status) {","        if(status) {","            dbConnected = true;","        }","    });","","    function onRequest(request, response) {        ","","        if(dbConnected) {","            var urlParts = url.parse(request.url, true);","\t    route(handle, urlParts, response, request);","        }","    }","   ","    var server = http.createServer(onRequest).listen(8888);","","    //start the chatserver","    chatServer.start(server);","}","","exports.start = start;"];
_$jscoverage['server.js'][1]++;
var http = require("http");
_$jscoverage['server.js'][2]++;
var url = require("url");
_$jscoverage['server.js'][3]++;
function start(route, handle, connectDB, chatServer) {
  _$jscoverage['server.js'][4]++;
  dbConnected = false;
  _$jscoverage['server.js'][5]++;
  connectDB((function (status) {
  _$jscoverage['server.js'][6]++;
  if (status) {
    _$jscoverage['server.js'][7]++;
    dbConnected = true;
  }
}));
  _$jscoverage['server.js'][11]++;
  function onRequest(request, response) {
    _$jscoverage['server.js'][13]++;
    if (dbConnected) {
      _$jscoverage['server.js'][14]++;
      var urlParts = url.parse(request.url, true);
      _$jscoverage['server.js'][15]++;
      route(handle, urlParts, response, request);
    }
}
  _$jscoverage['server.js'][19]++;
  var server = http.createServer(onRequest).listen(8888);
  _$jscoverage['server.js'][22]++;
  chatServer.start(server);
}
_$jscoverage['server.js'][25]++;
exports.start = start;
