/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['main.js']) {
  _$jscoverage['main.js'] = [];
  _$jscoverage['main.js'][1] = 0;
  _$jscoverage['main.js'][2] = 0;
  _$jscoverage['main.js'][3] = 0;
  _$jscoverage['main.js'][5] = 0;
  _$jscoverage['main.js'][6] = 0;
  _$jscoverage['main.js'][7] = 0;
  _$jscoverage['main.js'][8] = 0;
  _$jscoverage['main.js'][10] = 0;
}
_$jscoverage['main.js'].source = ["<span class=\"k\">var</span> server <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">'./server'</span><span class=\"k\">);</span>","<span class=\"k\">var</span> router <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">'./router'</span><span class=\"k\">);</span>","<span class=\"k\">var</span> requestHandlers <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">'./requestHandlers'</span><span class=\"k\">);</span>","","<span class=\"k\">var</span> handle <span class=\"k\">=</span> <span class=\"k\">{}</span><span class=\"k\">;</span>","handle<span class=\"k\">[</span><span class=\"s\">\"/save\"</span><span class=\"k\">]</span> <span class=\"k\">=</span> requestHandlers<span class=\"k\">.</span>save<span class=\"k\">;</span>","handle<span class=\"k\">[</span><span class=\"s\">\"/flag\"</span><span class=\"k\">]</span> <span class=\"k\">=</span> requestHandlers<span class=\"k\">.</span>flag<span class=\"k\">;</span>","handle<span class=\"k\">[</span><span class=\"s\">\"/getall\"</span><span class=\"k\">]</span> <span class=\"k\">=</span> requestHandlers<span class=\"k\">.</span>getAll<span class=\"k\">;</span>","","server<span class=\"k\">.</span>start<span class=\"k\">(</span>router<span class=\"k\">.</span>route<span class=\"k\">,</span> handle<span class=\"k\">);</span>"];
_$jscoverage['main.js'][1]++;
var server = require("./server");
_$jscoverage['main.js'][2]++;
var router = require("./router");
_$jscoverage['main.js'][3]++;
var requestHandlers = require("./requestHandlers");
_$jscoverage['main.js'][5]++;
var handle = {};
_$jscoverage['main.js'][6]++;
handle["/save"] = requestHandlers.save;
_$jscoverage['main.js'][7]++;
handle["/flag"] = requestHandlers.flag;
_$jscoverage['main.js'][8]++;
handle["/getall"] = requestHandlers.getAll;
_$jscoverage['main.js'][10]++;
server.start(router.route, handle);
