/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['server.js']) {
  _$jscoverage['server.js'] = [];
  _$jscoverage['server.js'][1] = 0;
  _$jscoverage['server.js'][2] = 0;
  _$jscoverage['server.js'][4] = 0;
  _$jscoverage['server.js'][6] = 0;
  _$jscoverage['server.js'][7] = 0;
  _$jscoverage['server.js'][8] = 0;
  _$jscoverage['server.js'][11] = 0;
  _$jscoverage['server.js'][15] = 0;
}
_$jscoverage['server.js'].source = ["<span class=\"k\">var</span> http <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"http\"</span><span class=\"k\">);</span>","<span class=\"k\">var</span> url <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"url\"</span><span class=\"k\">);</span>","","<span class=\"k\">function</span> start<span class=\"k\">(</span>route<span class=\"k\">,</span> handle<span class=\"k\">)</span> <span class=\"k\">{</span>","","    <span class=\"k\">function</span> onRequest<span class=\"k\">(</span>request<span class=\"k\">,</span> response<span class=\"k\">)</span> <span class=\"k\">{</span>","        <span class=\"k\">var</span> urlParts <span class=\"k\">=</span> url<span class=\"k\">.</span>parse<span class=\"k\">(</span>request<span class=\"k\">.</span>url<span class=\"k\">,</span> <span class=\"k\">true</span><span class=\"k\">);</span>  ","\troute<span class=\"k\">(</span>handle<span class=\"k\">,</span> urlParts<span class=\"k\">,</span> response<span class=\"k\">,</span> request<span class=\"k\">);</span>","    <span class=\"k\">}</span>","    ","    http<span class=\"k\">.</span>createServer<span class=\"k\">(</span>onRequest<span class=\"k\">).</span>listen<span class=\"k\">(</span><span class=\"s\">8888</span><span class=\"k\">);</span>","","<span class=\"k\">}</span>","","exports<span class=\"k\">.</span>start <span class=\"k\">=</span> start<span class=\"k\">;</span>"];
_$jscoverage['server.js'][1]++;
var http = require("http");
_$jscoverage['server.js'][2]++;
var url = require("url");
_$jscoverage['server.js'][4]++;
function start(route, handle) {
  _$jscoverage['server.js'][6]++;
  function onRequest(request, response) {
    _$jscoverage['server.js'][7]++;
    var urlParts = url.parse(request.url, true);
    _$jscoverage['server.js'][8]++;
    route(handle, urlParts, response, request);
}
  _$jscoverage['server.js'][11]++;
  http.createServer(onRequest).listen(8888);
}
_$jscoverage['server.js'][15]++;
exports.start = start;
